services:
  frontend:
    build:
      context: "frontend"
    depends_on:
      - "backend"
    ports:
      - "80:80"

  backend:
    build:
      context: "backend"
    depends_on:
      - "database"
    environment:
      DB_HOST: "database"
      DB_USER: "swipefood"
      DB_PASSWORD: "secret"
      DB_NAME: "swipefood"
      JWT_SECRET_FILE: "/var/run/secrets/jwt-secret"
    secrets:
      - "jwt-secret"

  database:
    image: "postgres:14-alpine"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "swipefood"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "swipefood"
      # TODO: add db init script

secrets:
  jwt-secret:
    file: "./jwt.secret"

volumes:
  db-data:
