services:
  frontend:
    build:
      context: "frontend"
    depends_on:
      - "backend"
    ports:
      - "80:80"

  backend:
    build:
      context: "backend"
    depends_on:
      - "database"
    environment:
      DB_HOST: "database"
      DB_USER: "swipefood"
      DB_PASSWORD: "secret"
      DB_NAME: "swipefood"
      # Demo mode, enables the /demo/init endpoint which populates the database with demo data
      # To disable, unset this environment variable (or set to empty string)
      DEMO_ENABLED: "true"
      JWT_SECRET_FILE: "/var/run/secrets/jwt-secret"
      SPOONACULAR_API_KEY_FILE: "/var/run/secrets/spoonacular-api-key"
    secrets:
      - "jwt-secret"
      - "spoonacular-api-key"

  # This service is responsible for setting up the database and is run as a one-off
  migrations:
    build:
      context: "backend"
      dockerfile: "migrations.dockerfile"
    restart: "on-failure"
    depends_on:
      - "database"
    environment:
      DB_HOST: "database"
      DB_USER: "swipefood"
      DB_PASSWORD: "secret"
      DB_NAME: "swipefood"

  database:
    image: "postgres:14-alpine"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "swipefood"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "swipefood"

secrets:
  jwt-secret:
    file: "./jwt.secret"
  spoonacular-api-key:
    file: "./spoonacular-api-key.secret"

volumes:
  db-data:
